[versions]
forge = "47.1.3"

curios = "5.8.1+1.20.1"

caelus = "3.2.0+1.20.1"

[libraries]
curios = { module = "top.theillusivec4.curios:curios-forge", version.ref = "curios" }

caelus = { module = "top.theillusivec4.caelus:caelus-forge", version.ref = "caelus" }
